[package]
name = "mtc"
version = "2.0.0"
edition = "2021"
license = "GPL3"

[dependencies]

[features]
bin = []

[lib]
name = "mtc"

[[bin]]
name = "mtc"
path = "src/main.rs"
required-features = ["bin"]

